import AppKit
import CryptoKit
import Security

struct Clip: Codable, Identifiable, Equatable, Sendable {
    var id = UUID()
    var copiedAt = Date()
    var source: String
    var items: [[String: Data]]
    var preview: String
    var kind: String

    var byteCount: Int { items.reduce(0) { $0 + $1.values.reduce(0) { $0 + $1.count } } }
    var imageData: Data? { items.first?[NSPasteboard.PasteboardType.png.rawValue] ?? items.first?[NSPasteboard.PasteboardType.tiff.rawValue] }
    var symbol: String { kind == "Image" ? "photo" : kind == "Files" ? "doc" : "text.alignleft" }

    static let supported: [NSPasteboard.PasteboardType] = [.fileURL, .URL, .string, .rtf, .html, .png, .tiff]
    static let ignored = Set([
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.RestoredType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping", "Pasteboard generator type"
    ])
    static let maximumBytes = 8 * 1_024 * 1_024

    static func capture(from pasteboard: NSPasteboard, source: String, now: Date = Date(), onLimit: (String) -> Void = { _ in }) -> Clip? {
        guard let originals = pasteboard.pasteboardItems, !originals.isEmpty,
              !originals.contains(where: { !$0.types.allSatisfy { !ignored.contains($0.rawValue) } }) else { return nil }
        guard originals.count <= 100 else {
            onLimit("Copy not saved: more than 100 clipboard items.")
            return nil
        }
        var size = 0
        var items: [[String: Data]] = []
        for original in originals {
            var representations: [String: Data] = [:]
            for type in supported where original.types.contains(type) {
                // Avoid asking the source app to generate a second image representation.
                if type == .tiff, representations[NSPasteboard.PasteboardType.png.rawValue] != nil { continue }
                guard let data = original.data(forType: type) else { continue }
                guard data.count <= maximumBytes - size else {
                    onLimit("Some clipboard formats exceeded the 8 MiB limit and were not saved.")
                    continue
                }
                size += data.count
                representations[type.rawValue] = data
            }
            // Keep multi-item copies intact; skip formats we cannot restore.
            guard !representations.isEmpty else { return nil }
            items.append(representations)
        }
        let files = items.compactMap { $0[NSPasteboard.PasteboardType.fileURL.rawValue] }
            .compactMap { String(data: $0, encoding: .utf8) }.compactMap(URL.init(string:))
        let text = items.compactMap { $0[NSPasteboard.PasteboardType.string.rawValue] }
            .compactMap { String(data: $0, encoding: .utf8) }.joined(separator: "\n")
        let hasImage = items.contains { $0[NSPasteboard.PasteboardType.png.rawValue] != nil || $0[NSPasteboard.PasteboardType.tiff.rawValue] != nil }
        let kind = !files.isEmpty ? "Files" : hasImage ? "Image" : "Text"
        let preview = !files.isEmpty ? files.map(\.lastPathComponent).joined(separator: ", ") : !text.isEmpty ? String(text.prefix(20_000)) : hasImage ? "Copied image" : "Formatted text"
        guard size > 0 else { return nil }
        return Clip(copiedAt: now, source: source, items: items, preview: preview, kind: kind)
    }

    func restore(to pasteboard: NSPasteboard) -> Bool {
        let restored = items.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: .init(type)) }
            item.setString("", forType: .init("org.nspasteboard.source"))
            return item
        }
        guard !restored.isEmpty else { return false }
        pasteboard.clearContents()
        return pasteboard.writeObjects(restored)
    }
}

struct History: Codable, Sendable {
    let version = 1
    var clips: [Clip] = []
    static let maximumBytes = 32 * 1_024 * 1_024

    private enum CodingKeys: String, CodingKey { case version, clips }

    init(clips: [Clip] = []) { self.clips = clips }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let version = try container.decodeIfPresent(Int.self, forKey: .version) ?? 1
        guard version == 1 else { throw VaultError.unsupportedVersion(version) }
        clips = try container.decode([Clip].self, forKey: .clips)
    }

    mutating func insert(_ clip: Clip, hours: Double, limit: Int, now: Date = Date()) {
        clips.removeAll { $0.items == clip.items }
        clips.insert(clip, at: 0)
        purge(hours: hours, limit: limit, now: now)
    }

    @discardableResult
    mutating func purge(hours: Double, limit: Int, now: Date = Date()) -> Bool {
        let oldIDs = clips.map(\.id)
        let cutoff = now.addingTimeInterval(-max(1, min(hours.isFinite ? hours : 24, 8_760)) * 3_600)
        clips.removeAll { $0.copiedAt <= cutoff || $0.byteCount > Clip.maximumBytes }
        clips.sort { $0.copiedAt > $1.copiedAt }
        var bytes = 0
        clips = Array(clips.prefix(max(1, min(limit, 500))).prefix { clip in
            bytes += clip.byteCount
            return bytes <= Self.maximumBytes
        })
        return oldIDs != clips.map(\.id)
    }
}

enum VaultError: LocalizedError {
    case keychain(OSStatus), missingKey, invalidFile, unsupportedVersion(Int)
    var errorDescription: String? {
        switch self {
        case .keychain(let status): return "Keychain is unavailable (\(status)). Unlock your Mac and retry."
        case .missingKey: return "The encryption key is missing. Existing history has been left untouched."
        case .invalidFile: return "Saved history could not be opened. Existing history has been left untouched."
        case .unsupportedVersion(let version): return "History version \(version) needs a newer Clip History app. Existing history has been left untouched."
        }
    }
}

struct Vault: Sendable {
    let url: URL
    let key: SymmetricKey

    static func open() throws -> Vault {
        let folder = try FileManager.default.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
            .appendingPathComponent("ClipHistory", isDirectory: true)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        var resourceURL = folder
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        try resourceURL.setResourceValues(values)
        let url = folder.appendingPathComponent("history.encrypted")
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: "local.cliphistory.encryption",
            kSecAttrAccount as String: "history-key"
        ]
        var result: CFTypeRef?
        let status = SecItemCopyMatching(query.merging([
            kSecReturnData as String: true, kSecMatchLimit as String: kSecMatchLimitOne
        ]) { _, new in new } as CFDictionary, &result)
        if status == errSecSuccess, let data = result as? Data, data.count == 32 {
            return Vault(url: url, key: SymmetricKey(data: data))
        }
        guard status == errSecItemNotFound else { throw VaultError.keychain(status) }
        guard !FileManager.default.fileExists(atPath: url.path) else { throw VaultError.missingKey }
        let key = SymmetricKey(size: .bits256)
        let addStatus = SecItemAdd(query.merging([
            kSecValueData as String: key.withUnsafeBytes { Data($0) },
            kSecAttrAccessible as String: kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            kSecAttrLabel as String: "Clip History encryption key"
        ]) { _, new in new } as CFDictionary, nil)
        guard addStatus == errSecSuccess else { throw VaultError.keychain(addStatus) }
        return Vault(url: url, key: key)
    }

    func load() throws -> History {
        guard FileManager.default.fileExists(atPath: url.path) else { return History() }
        guard (try url.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0) <= 64 * 1_024 * 1_024 else { throw VaultError.invalidFile }
        do {
            let sealed = try AES.GCM.SealedBox(combined: Data(contentsOf: url))
            let data = try AES.GCM.open(sealed, using: key)
            return try PropertyListDecoder().decode(History.self, from: data)
        } catch let error as VaultError { throw error }
        catch { throw VaultError.invalidFile }
    }

    func save(_ history: History) throws {
        // ponytail: one encrypted snapshot, bounded to 32 MB; use SQLite if history grows beyond this.
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .binary
        let data = try encoder.encode(history)
        guard let encrypted = try AES.GCM.seal(data, using: key).combined else { throw VaultError.invalidFile }
        try encrypted.write(to: url, options: .atomic)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }
}

// One serial executor for disk and Keychain work; a failed load never enables writes.
actor HistoryStorage {
    private var vault: Vault?
    private var loaded = false

    init(vault: Vault? = nil) { self.vault = vault }

    func load() throws -> History {
        loaded = false
        let opened = try vault ?? Vault.open()
        let history = try opened.load()
        vault = opened
        loaded = true
        return history
    }

    func save(_ history: History) throws {
        try Task.checkCancellation()
        guard loaded, let vault else { throw VaultError.invalidFile }
        try vault.save(history)
    }
}
